### ISSUE TITLE
[BUG] Replay buffer crashing in example dreamer.py 

### ISSUE THREAD

**Issue by atonkamanda** [pytorch/rl#844]
## Describe the bug

https://github.com/pytorch/rl/blob/main/examples/dreamer/dreamer.py
In the dreamer example the line 234  replay_buffer.extend(tensordict.cpu()) cause this bug 
```bash
Creating a MemmapStorage...
The storage is being created: 
/Tmp/anaconda3/envs/torchrl/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Killed
```

## To Reproduce

Run dreamer.py with python3.9 or 3.10 

## Expected behavior

The script to be running normally 

## Reason and Possible fixes

From what I've read, this bug is occurring in python3.9/3.10 with multiprocessing. I haven't found a way to jump around it any suggestion ? Also, I would like to request to make the examples in the tutorial more suited for a single simple GPU run since I think most of the people that will be learning the library using this example. 
Thank you very much.

## Checklist

- [ ] I have checked that there is no similar issue in the repo (**required**)
- [ ] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [ ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for reporting this we'll have a look at this asap.
Thanks also for the suggestion. Can you try using a LazyTensorStorage (instead of a LazyMemmap)? You'll be storing things in RAM instead of physical storage but that should work ok.
In the meantime can you share your config (besides python version) incl. os, pytorch version etc?

**Comment by atonkamanda** [comment]
Hello, thank for fast and dedicated answer  !

I tried LazyTensorStorage and deprecating to python3.7 but I got the same error 

```bash
init seed: 42, final seed: 1445067485
800it [00:02, 314.33it/s]                                                                                                  torch.Size([1, 800])
Creating a TensorStorage...
/Tmp/anaconda3/envs/torchrl_stable/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Killed

```

But I finally managed to fix it by putting all config files batch sizes to minimal values, so I guess it was just trying to allocate too much memory !

I don't know what fixed it since I changed everything altogether but I did ran with this. 
config.yaml
```yaml

env_name: cheetah
env_task: run
env_library: dm_control
catframes: 1
async_collection: False
record_video: 0
frame_skip: 1
batch_size: 50
batch_length: 50
total_frames: 100
world_model_lr: 6e-4
actor_value_lr: 8e-5
from_pixels: True
# we want 50 frames / traj in the replay buffer. Given the frame_skip=2 this makes each traj 100 steps long
env_per_collector: 1
num_workers: 1
# collector_devices: [cuda:1]
collector_devices: cuda:0  # [cpu,cpu,cpu,cpu,cpu,cpu,cpu,cpu]
frames_per_batch: 100
optim_steps_per_batch: 80
record_interval: 30
max_frames_per_traj: 100
record_frames: 100
batch_transform: 1
state_dim: 30
rssm_hidden_dim: 200
grad_clip: 100
grayscale: False
image_size : 64
buffer_size: 100
init_env_steps: 1000
init_random_frames: 1000
logger: csv
offline_logging: False
normalize_rewards_online: True
normalize_rewards_online_scale: 5.0
normalize_rewards_online_decay: 0.99999
reward_scaling: 1.0
```
replay_buff size in config to 10 and also all other configs minimal values.

I think you can't close the issue if you don't need further information from my part.

Again thanks for reactivity I will keep usingthe very cool library you provided us here to do my research so I might come back if I can help !
